# Dependabot configuration for Gradle dependencies, Docker images and Github Actions.

version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"  # Weekdays only
      time: "00:01"
      timezone: "Europe/Copenhagen"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "github-actions"
    # For github actions, / means `.github/workflows` instead of repository root
    directory: "/"
    schedule:
      interval: "daily" # Weekdays only
      time: "00:01"
      timezone: "Europe/Copenhagen"
    pull-request-branch-name:
      separator: "-"
