version: v16.1.0

files:
  - .github/workflows/format-kotlin.yaml
  - .github/workflows/pr-help.yaml
  - .github/workflows/release.yaml
  - .github/workflows/verify-release.yaml
  - .autorc.json
  - .github/workflows/opslevel.yaml
  - .github/workflows/snyk.yaml

values:
  autoRelease: true
  sendOpsLevelDeployNotifications: true
  sendOpsLevelVulnerabilityCheck: true
