version: v34.10.1

files:
  - .github/workflows/build-and-test.yaml
  - .github/workflows/codeql-analysis.yaml
  - .github/workflows/pr-help.yaml
  - .github/workflows/release.yaml
  - .github/workflows/renovate_dependency_management.yaml
  - .autorc.json
  - .github/.kodiak.toml

values:
  sendOpsLevelDeployNotifications: true
  deploymentEnabled: false
  runWizCliDepsScan: false
  renovateCronjobSchedule: '25 6 * * 1-5' # This is UTC -> At 07:25 CET / 08:25 CEST on every day-of-week from Monday through Friday.
