version: v34.6.0

files:
  - .autorc.json
  - .github/.kodiak.toml
  - .github/workflows/build-and-test.yaml
  - .github/workflows/codeql-analysis.yaml
  - .github/workflows/pr-help.yaml
  - .github/workflows/release.yaml

values:
  autoRelease: true
  allowKodiakAutoMerge: true
  defaultBranch: main
  sendOpsLevelDeployNotifications: true
  sendOpsLevelVulnerabilityCheck: true
  deploymentEnabled: false
  runWizCliDepsScan: false
