version: v20.13.10

files:
  - .github/.kodiak.toml
  - .github/workflows/format-kotlin.yaml
  - .github/workflows/release.yaml
  - .github/workflows/verify-release.yaml
  - .autorc.json
  - .github/workflows/pr-help.yaml
  - .github/workflows/assign-random-codeowner.yaml
  - .github/workflows/build-and-test.yaml
  - .github/workflows/codeql-analysis.yaml


values:
  autoRelease: true
  allowKodiakAutoMerge: true
  defaultBranch: main
  sendOpsLevelDeployNotifications: true
  sendOpsLevelVulnerabilityCheck: true
  deploymentEnabled: false
