version: v18.1.0

files:
  - .github/.kodiak.toml
  - .github/workflows/format-kotlin.yaml
  - .github/workflows/release.yaml
  - .github/workflows/verify-release.yaml
  - .autorc.json
  - .github/workflows/pr-help.yaml
  - .github/workflows/assign-random-codeowner.yaml
  - .github/workflows/build-and-test.yaml


values:
  autoRelease: true
  allowKodiakAutoMerge: true
  defaultBranch: master
  sendOpsLevelDeployNotifications: true
  sendOpsLevelVulnerabilityCheck: true
