language: java
jdk:
- openjdk8
env:
  global:
  - secure: qbeLB5BZHR89cfmc+mvGFTnViATpsYq5QoQyNi7BRAbgLh4G0C0hml8DXXcuBRItN96xTrGQ0DbHhG+DTQhzhuc6VrBrlTTqwHIUy99MIakukC+qWYjwxMdT1YIEzXdsA//kI6ZPld5jnPhcIPAK152qywH2bCxmTl/XOjEA+dB0n0FKZ2nEp5xawOJ0lbSFIHAgJIBwVscE87eW16QI00SzvzT0T+dS9AyeW5k6qQttaS3njB3aLF3ixa5nC/0md9ezPzekKubN9JS0R3Fkgp3jGACMWG/tUPQYkUXirviLnMy1Fg+m7RV8ATMPg+O3LjLJZ05euG5z6TP+XEKB7k9lcEXaOoKUiKJrWG56X0dIEhEoFYP9gb8c/E0WP/zba7JFQ8SCl+5HRjmaZAjVe7VTrbob4Cq/PM9p+LlOLWRscH4FinliWZBlJ05ZgFao4aLMbGov6rDAesZBDLId2V2Kjd/eIGjnVy0N4io4An3YqBcjWrCVNisbwiR00ze5rfWsmZsUFJxrahmakBBYMAU/zdEpc0TtJTiudsWCaWbhPCiEJYiW1k8ScNTK7vJdwGmv2o/mNGsWy2oUoCQ8XQn+nDNvU82//j6wYdpnIgtO/2O3qh1knPFQYUHFsPkQesk9yf8DuIT6gyEubyXtzClWISuXiNkr8ueCY3JEZhU=
  - secure: wQUkLdLFlyiV7jA14gC8csqfr76TzQWQwZ5u+jawM1csTHBHBt8+28kkUegmJuh6+GSnlERKFBKWm9aQKxEkY2SP7RV/HQ6ET05YiS5q6wZfMfjo1NgRNWvHRaRbkO4v5U1wguEDFiLvMPJyFhlLaE0N7T/PdbhKo/YdqhQtJeVkyeahWcam9UPuStcByuju1sSbTkKfcYpiIXC3Hcd/EH2NRrd77JDZ2lJ+oZh5TKSqZPrWWakeFF6NLmNzRgVQ0vbyccx2CuLBUh8JARpwogv5Zja6GrRQh91w3RsXI9i4VvmyFmSQCd4SiGa2wN+AO240fzgvjDbCKTyJShhgtgtFFp1b9eXPk5wc2JFr+s6mwu4Af068RxSt36WQ0BhOkid8pey6yWYp6vdOwYBDgelYP4uBeopwLQ3bH86SAPiZCQ8eCxX1kpNuZZRkj1j0MCmTJlIrlihTZc3KYH+ErstL83vmlR6OQhasRD6mV130tBJE62hdRgghWtklsYheFMDkXPEydR+SubewHT2L7SII1Acgg8Gvm2gALJ6VDwAQJwD9aQ4HUIFkBO/C/V5hKPwAb8TDPkLyoZhtdnlZbA7SG5LSHyOMcwvPfddjD+Hh+9pJyYoW8dYtITRvs0VrwpoZp4EmmJJf4eO0tNkZGxAzzc6NzqxKunHAxC5fQ+E=
  - secure: iQQst09s+V2bv+UAxDLhx2LkebN4TjIPEdaWUKdQDfzx13nrha47JAMQfsSdviv7FH8Aj+/XFgxJPGECpHbETdXhjwu6GpAOu2V0daRP8RFtU7jf47hCnuPynVvThDwdS25Z6OOrffW7OjOJd8iLu/2nUBSV7N7yRbSyX2yWFUntVPKQoow+4VDqlxydyteXsnoIlI6jCl3EMMV/CqZ8sj58/y0280d22Q31ywO/3FKJUxsergKz+BRUDUb8mjOnvsJCT5dd1NUoU9McoCWb7DJuOSizSHmEXFEgvkbGIZghTr0qTY90k/WQmKsZM0Bi5xACW0Gs+BTSV4jr2GzJBQK2ln5sJzMg+NQv2VMEi8RvADnGMtKMiJ28eMx3AHdKagdfAsHjRe21pCKk1kqVgEfLpttR4oAAW1OWZv0FXVa8Ocf82mdgHhmjEhUd2BRV/VdsGNR+VqD9MYHWJqQQIrl/Z18VRVy7ewKhjCv8av85N3WTsPUl6JmDF7WJKJbEnnE+NLUSVV7NMbAmaYhUzyvHWZjAGZiraGoU6OytvD6lMjvt4i6O1v41Oig6b1ijPSCn81i3YxWgsXYFaMidmSHhgkDJkkJH+ZMhb9jVEYrEmRRBUtPg2iZodWLksDwfeeOgzPFtV8QvlKcNeHre1hFGhQgcq/cdNoVS+ISa6O4=
before_install:
- openssl aes-256-cbc -K $encrypted_8beedd6ac280_key -iv $encrypted_8beedd6ac280_iv
  -in secring.gpg.enc -out secring.gpg -d
script:
- ./gradlew -Prelease -Psigning.keyId=3A7308BC -Psigning.password=$GPG_PASSPHRASE -Psigning.secretKeyRingFile=$(pwd)/secring.gpg clean build
deploy:
  skip_cleanup: true
  provider: script
  script: ./gradlew -Prelease -Psigning.keyId=3A7308BC -Psigning.password=$GPG_PASSPHRASE -Psigning.secretKeyRingFile=$(pwd)/secring.gpg uploadArchives closeAndPromoteRepository
  on:
    tags: true
cache:
  directories:
  - .gradle
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

notifications:
  email: false